OldSuply/OldSuply/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('app.urls')),
    path("cart/", include('cart.urls')),
    path('checkout/', include('pedidos.urls'))
]

OldSuply/app/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('novidades', views.novidades, name='novidades'),
    path('register/', views.registrar, name='registrar'),
    path('login/', views.logar, name='logar'),
    path('logout/', views.logout_view, name='lougout'),
    path('profile/<username>', views.profile_view, name='profile'),
    path('profile/<username>/edit/', views.edit_profile, name='edit'),
    path('profile/<username>/order/<order_id>', views.order_info, name='order_info'),
    path('products/', views.products_view, name='produtos'),
    # path('products/', views.ProductListView.as_view()),
    path('products/<slug:slug>/', views.ProductDetailSlugView.as_view())
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

OldSuply/cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path('', views.cart_home, name='home'),
    path('update/', views.cart_update, name='update')
]

OldSuply/cart/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save, post_save, m2m_changed
from django.contrib.auth.models import AnonymousUser
from app.models import Product

User = settings.AUTH_USER_MODEL
class CarrinhoManager(models.Manager):
    def new_or_get(self, request):

        cart_id = request.session.get("cart_id", None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = Carrinho.objects.new(user=request.user)
            new_obj = True
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj
    
    def new(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                user_obj = user
        return self.model.objects.create(user=user_obj)

class Carrinho(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    products = models.ManyToManyField(Product, blank= True)
    total = models.DecimalField(default=0.00, max_digits=65, decimal_places=2)
    # subtotal = models.DecimalField(default=0.00, max_digits=65, decimal_places=2)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = CarrinhoManager()

    def __str__(self):
        return str(self.id)

def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
  if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
    products = instance.products.all() 
    total = 0 
    for product in products: 
      total += product.price 
    # if instance.subtotal != total:
    #   instance.subtotal = total
    #   instance.save()
    instance.total = total
    instance.save()

m2m_changed.connect(m2m_changed_cart_receiver, sender = Carrinho.products.through)

# def pre_save_cart_receiver(sender, instance, *args, **kwargs):
#     if instance.subtotal > 0:
#         instance.total = instance.subtotal  + 10 # considere o 10 como uma taxa de entrega
#     else:
#         instance.total = 0.00

# pre_save.connect(pre_save_cart_receiver, sender = Carrinho)

OldSuply/cart/views.py
from .models import Carrinho
from app.models import Product, Address
from django.shortcuts import render, redirect

def cart_home(request):
    address = None
    if request.user.is_authenticated:
        address = Address.objects.filter(address_id=request.user).first()
    cart_obj, new_obj = Carrinho.objects.new_or_get(request)
    products = cart_obj.products.all()
    return render(request, "cart.html", {"cart": cart_obj, "products": products, 'address': address})

def cart_update(request):
    # print(request.POST)
    product_id = request.POST.get('product_id')
    if product_id is not None:
        try:
            product_obj = Product.objects.get(product_id=product_id)
        except Product.DoesNotExist:
            print("Mostrar mensagem ao usuário, esse produto acabou!")
            return redirect("cart:home")

    cart_obj, new_obj = Carrinho.objects.new_or_get(request)
    if product_obj in cart_obj.products.all():
        cart_obj.products.remove(product_obj)
    else:
        cart_obj.products.add(product_obj)
    request.session['cart_items'] = cart_obj.products.count()
    return redirect("cart:home")

OldSuply/cart/templates/cart.html
{% extends 'base2.html' %}
{% load static %}
{% block css_path %}
  <link rel="stylesheet" href="{% static 'cart/css/cart.css' %}" />
{% endblock %}



{% block content %}
<section class="h-100 h-custom" style="background-color: #eee;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col">
        <div class="card">
          <div class="card-body p-4">

            <div class="row">

              <div class="col-lg-7">
                <h5 class="mb-3"><a href="/" class="text-body"><i
                      class="fas fa-long-arrow-alt-left me-2"></i>Continue comprando</a></h5>
                <hr>

                <div class="d-flex justify-content-between align-items-center mb-4">
                  <div>
                    <p class="mb-1">Seu carrinho</p>
                  </div>
                </div>
                {% for product in products %}
                <div class="card mb-3">
                  <div class="card-body">
                    <div class="d-flex justify-content-between">
                      <div class="d-flex flex-row align-items-center">
                        <div>
                          <img
                            src="{{ product.image.url }}"
                            class="img-fluid rounded-3" alt="Shopping item" style="width: 65px;">
                        </div>
                        <div class="ms-3">
                          <h5>{{ product.name }}</h5>
                        </div>
                      </div>
                      <div class="d-flex flex-row align-items-center">
                        <div style="width: 80px;">
                          <h5 class="mb-0">R${{ product.price }}</h5>
                        </div>
                        {% include 'update-cart.html' with product=product cart=cart in_cart=True %}
                      </div>
                    </div>
                  </div>
                </div>
                {% endfor %}

                
              </div>
              <div class="col-lg-5">
                {% if request.user.is_authenticated %}

                {% if not address %}
                <div class="card bg-primary text-white rounded-3">
                  <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center mb-4">
                      <h5 class="mb-0">Endereço de entrega</h5>
                    </div>
                    
                    <form id="infos" class="mt-4" action="/checkout/" method="POST"> {% csrf_token %}
                      <div class="form-outline form-white mb-4">
                        <input type="text" id="city" name='city' class="form-control form-control-lg" siez="17"
                          placeholder="Brasília" />
                        <label class="form-label" for="city">Cidade</label>
                      </div>

                      <div class="form-outline form-white mb-4">
                        <input type="text" id="state" name='state' class="form-control form-control-lg" siez="17"
                          placeholder="Distrito Federal"/>
                        <label class="form-label" for="state">Estado</label>
                      </div>

                      <div class="form-outline form-white mb-4">
                        <input type="text" id="street" name='street' class="form-control form-control-lg" siez="17"
                          placeholder="Rua Joaquim Alves" />
                        <label class="form-label" for="street">Logradouro</label>
                      </div>

                      <div class="form-outline form-white mb-4">
                        <input type="text" id="bairro" name='bairro' class="form-control form-control-lg" siez="17"
                          placeholder="Asa Sul" />
                        <label class="form-label" for="bairro">Bairro</label>
                      </div>

                      <div class="row mb-4">
                        <div class="col-md-6">
                          <div class="form-outline form-white">
                            <input type="text" id="cep" name='cep' class="form-control form-control-lg"
                              placeholder="70050000" size="7" minlength="8" maxlength="8" />
                            <label class="form-label" for="cep">CEP</label>
                          </div>
                        </div>
                        <div class="col-md-6">
                          <div class="form-outline form-white">
                            <input type="text" id="number" name='number' class="form-control form-control-lg"
                            placeholder="230" size="1" minlength="1"/>
                            <label class="form-label" for="number">Número</label>
                          </div>
                        </div>
                      </div>
                    </form>

                    <hr class="my-4">

                    <div class="d-flex justify-content-between">
                      <p class="mb-2">Subtotal</p>
                      <p class="mb-2">R${{ cart.total }}</p>
                    </div>

                    <div class="d-flex justify-content-between">
                      <p class="mb-2">Taxa de entrega</p>
                      <p class="mb-2">A calcular</p>
                    </div>

                    <button form="infos" type="submit" class="btn btn-info btn-block btn-lg">
                      <div class="d-flex justify-content-between">
                        <span>Checkout <i class="fas fa-long-arrow-alt-right ms-2"></i></span>
                      </div>
                    </button>
                    {% else %}
                      <p>CONFIRME SEU ENDEREÇO</p>
                      <p>Cidade: {{ address.city }}</p>
                      <p>Estado: {{ address.state }}</p>
                      <p>CEP: {{ address.cep }}</p>
                      <p>Logradouro: {{ address.street_address }}, {{ address.number }}</p>
                      <p>Bairro: {{ address.bairro }}</p>
                      
                      <hr class="my-4">

                    <div class="d-flex justify-content-between">
                      <p class="mb-2">Subtotal</p>
                      <p class="mb-2">R${{ cart.total }}</p>
                    </div>

                    <div class="d-flex justify-content-between">
                      <p class="mb-2">Taxa de entrega</p>
                      <p class="mb-2">A calcular</p>
                    </div>

                    <a href="/checkout/" class="btn btn-info btn-blocl btn-lg">Calcular frete</a>
                    {% endif %}
                    {% else %}
                      <h2>Para continuar a compra, você precisa estar registrado/logado</h2>
                      <a href="/login/" class="btn btn-success">Logar</a>
                      <a href="/register/" class="btn btn-success">Registrar</a>
                    {% endif %}
                  </div>
                </div>

              </div>

            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

OldSuply/cart/templates/update-cart.html
<form method='POST' action='{% url "cart:update" %}' class="form"> {% csrf_token %}
    <input type='hidden' name='product_id' value='{{ product.product_id }}' />
    {% if product in cart.products.all %}
      <button type='submit' class='btn btn-danger'>Remover?</button>
    {% else %}
      <button type='submit' class='btn btn-success'>Adicionar</button>
    {% endif %}
</form>