OldSuply/OldSuply/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('app.urls')),
    path("cart/", include('cart.urls')),
    path('checkout/', include('pedidos.urls'))
]

OldSuply/app/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('novidades', views.novidades, name='novidades'),
    path('register/', views.registrar, name='registrar'),
    path('login/', views.logar, name='logar'),
    path('logout/', views.logout_view, name='lougout'),
    path('profile/<username>', views.profile_view, name='profile'),
    path('profile/<username>/edit/', views.edit_profile, name='edit'),
    path('profile/<username>/order/<order_id>', views.order_info, name='order_info'),
    path('products/', views.products_view, name='produtos'),
    # path('products/', views.ProductListView.as_view()),
    path('products/<slug:slug>/', views.ProductDetailSlugView.as_view())
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

OldSuply/pedidos/urls.py
from django.urls import path
from . import views

app_name = "checkout"

urlpatterns = [
    path('', views.checkout, name='checkout'),
    path('update/', views.checkout_update, name='update'),
    # path('pagamento/', views.gerar_qr, name='payment')
    path('pagamento/<order_id>', views.payment, name='payment')
]

OldSuply/pedidos/models.py
import math

from django.db import models
from django.db.models.signals import pre_save, post_save

from app.models import Address
from cart.models import Carrinho
from app.utils import unique_order_id_generator
# Create your models here.

ORDER_STATUS = (
    ('created', 'Criado'),
    ('paid', 'Pago'),
    ('shipped', 'Enviado'),
    ('refunded', 'Devolvido'),
)

class Pedidos(models.Model):

    order_id = models.CharField(max_length=128, blank=True)
    order_status = models.CharField(max_length=64, default='created', choices=ORDER_STATUS)
    address = models.ForeignKey(Address, on_delete=models.CASCADE, null=True, blank=True)
    cart = models.ForeignKey(Carrinho, on_delete=models.CASCADE, null=True, blank=True)
    preco_prazo = models.DecimalField(default=0, max_digits=64, decimal_places=2)
    total = models.DecimalField(default=0, max_digits=64, decimal_places=2)

    def update_total(self):
        total, preco = self.cart.total, self.preco_prazo
        self.total = format(math.fsum([total, preco]))
        # self.total = total + preco
        self.save()
        return self.total
    
    def __str__(self):
        return self.order_id

def pre_save_create_order_id(sender, instance, *args, **kwargs):
    if not instance.order_id:
        instance.order_id = unique_order_id_generator(instance)

pre_save.connect(pre_save_create_order_id, sender=Pedidos)

def post_save_cart_total(sender, instance, created, *args, **kwargs):
    if not created:
        cart_obj = instance
        cart_total = cart_obj.total
        cart_id = cart_obj.id
        qs = Pedidos.objects.filter(cart__id=cart_id)
        if qs.count() == 1:
            order_obj = qs.first()
            order_obj.update_total()

post_save.connect(post_save_cart_total, sender=Carrinho)

def post_save_order(sender, instance, created, *args, **kwargs):
    print("Executando")
    if created:
        print("Atualizando")
        instance.update_total()

post_save.connect(post_save_order, sender=Pedidos)

OldSuply/pedidos/forms.py
# Fazer o form input radio pra alterar o valor do carrinho + frete
from django import forms

class FreteForm(forms.Form):
    fretes_choice = forms.ChoiceField(widget=forms.RadioSelect)

OldSuply/pedidos/views.py
import requests
import os

from .forms import FreteForm
from .models import Pedidos
from app.models import Address
from cart.models import Carrinho

from dotenv import load_dotenv, find_dotenv
from django.shortcuts import render, redirect
# Create your views here.

def checkout(request):
    if request.method == "POST":
        a = Address(address_id=request.user,
                    street_address=request.POST['street'],
                    number=request.POST['number'],
                    bairro=request.POST['bairro'],
                    city=request.POST['city'],
                    state=request.POST['state'],
                    cep=request.POST['cep'])
        a.save()
    cart_obj, cart_created = Carrinho.objects.new_or_get(request)
    order_obj = None

    if cart_created or cart_obj.products.count() == 0:
        if 'order_id' in request.session:
            order_obj = Pedidos.objects.filter(order_id=request.session['order_id']).first()
        else:
            return redirect("cart:home")
    else:
        order_obj, new_order_obj = Pedidos.objects.get_or_create(cart=cart_obj)
        order_obj.address = Address.objects.filter(address_id=request.user).first()
        order_obj.save()
        request.session['cart_items'] = 0
        request.session['order_id'] = order_obj.order_id
        del request.session['cart_id']

    load_dotenv(find_dotenv())
    url = "https://sandbox.superfrete.com/api/v0/calculator"

    payload = {
        "from": { "postal_code": "37600000" },
        "to": { "postal_code": f"{order_obj.address.cep}" },
        "services": "1,2,17",
        "options": {
            "own_hand": False,
            "receipt": False,
            "insurance_value": 0,
            "use_insurance_value": False
        },
        "package": {
            "height": 2,
            "width": 11,
            "length": 16,
            "weight": 0.3
        }
    }
    headers = {
        "accept": "application/json",
        "User-Agent": "Nome e versão da aplicação (email para contato técnico)",
        "content-type": "application/json",
        "Authorization": f"Bearer {os.environ.get('FRETE_TOKEN')}"
        }


    response = requests.post(url, json=payload, headers=headers)
    resposta = response.json()

    form = FreteForm()
    choices = []
    for i in resposta:
        choices.append((i.get('id'), f'{i["name"]} -- Preço: R${i["price"]} -- Chega em até {i["delivery_time"] } dias.'))
    form.fields["fretes_choice"].choices = choices
    return render(request, "checkout.html", {"object": order_obj, 'form_frete': form})

def checkout_update(request):

    order_obj= Pedidos.objects.filter(order_id=request.session['order_id']).first()

    load_dotenv(find_dotenv())
    url = "https://sandbox.superfrete.com/api/v0/calculator"

    payload = {
        "from": { "postal_code": "37600000" },
        "to": { "postal_code": f"{order_obj.address.cep}" },
        "services": "1,2,17",
        "options": {
            "own_hand": False,
            "receipt": False,
            "insurance_value": 0,
            "use_insurance_value": False
        },
        "package": {
            "height": 2,
            "width": 11,
            "length": 16,
            "weight": 0.3
        }
    }
    headers = {
        "accept": "application/json",
        "User-Agent": "Nome e versão da aplicação (email para contato técnico)",
        "content-type": "application/json",
        "Authorization": f"Bearer {os.environ.get('FRETE_TOKEN')}"
        }

    response = requests.post(url, json=payload, headers=headers).json()

    # order_obj.preco_prazo = resposta[request.POST.fetes_choice]
    for i in response:
        if i.get('id') == int(request.POST['fretes_choice']):
            order_obj.preco_prazo = i.get('price')
            order_obj.save()
            order_obj.update_total()
    return redirect('checkout:checkout')

def payment(request, order_id):
    if 'order_id' in request.session:
        del request.session['order_id']
    order_obj = Pedidos.objects.filter(order_id=order_id).first()

    return render(request, 'payment_pix_fix.html', {'order': order_obj})
    
#fazer um blg q quando finaliza o pedido tira 1 do 'stock' no produto

# def gerar_qr(request):
#     cart_obj, cart_created = Carrinho.objects.new_or_get(request)
#     order_obj, new_order_obj = Pedidos.objects.get_or_create(cart=cart_obj)

#     preco = str(order_obj.total)
#     preco = preco.replace('.', '')
#     url = "https://sandbox.api.pagseguro.com/orders"

#     payload = {
#         "customer": {
#             "tax_id": "12345678909",
#             "email": f"{cart_obj.user.email}",
#             "name": f"{cart_obj.user.name}"
#         },
#         "reference_id": f"{order_obj.order_id}",
#         "qr_codes": [{ "amount": { "value": f'{preco}' } }]
#     }
#     headers = {
#         "accept": "application/json",
#         "Authorization": "0DBA84D4CDE844E0B23CD2FFF403E32F",
#         "content-type": "application/json"
#     }

#     # usando o modo sandbox até vai, mas precisa de permissão deleas pra deixar o trem em produção
#     # tenta criar conta no mercado pago
#     response = requests.post(url, json=payload, headers=headers)
#     resposta = response.json()
#     qr_link = resposta.get('qr_codes')[0].get('links')[0].get('href')

#     return render(request, "payment.html", {"object": order_obj, 'qr_link': qr_link})

OldSuply/pedidos/templates/checkout.html
{% extends "base.html" %}
{% block content %}
<div class="container bg-light">
{% include 'choose_shipping.html' with form_frete=form_frete %}
  <h1>Checkout</h1>
  <p>Produtos:</p>
  <p>
    {% for i in object.cart.products.all %}
      {% if forloop.last %}
        <b>{{ i.name }}</b>
      {% else %}
      <b>{{ i.name }},</b>
      {% endif %}
    {% endfor %}
  </p>
  <p>Total do carrinho: {{ object.cart.total }}</p>
  <p>Frete: {{ object.preco_prazo}}</p>
  <p>total: {{ object.total }}</p>
  {% if object.preco_prazo != 0 %}
    <a href="pagamento/{{ object.order_id }}" class="btn btn-success">Pagar</a>
  {% endif %}
</div>
{% endblock %}

OldSuply/pedidos/templates/choose_shipping.html
<form method='POST' action='{% url "checkout:update" %}' class="form"> {% csrf_token %}
    {% for field in form_frete %}
        {{ field}}
    {% endfor %}
    <button type='submit' class='btn btn-success'>Calcular</button>
</form>

<!-- <form action="{% url 'checkout:update' %}" method="post">
    {% csrf_token %}
    {{ form }}
</form> -->

OldSuply/pedidos/templates/payment.html
{% extends "base.html" %}
{% block content %}
<div class="bg-light">
    <img src="{{ qr_link }}" alt="">
</div>
{% endblock %}

OldSuply/pedidos/templates/payment_dynamic.html
{% extends "base.html" %}
{% block content %}
<div class="bg-light">
    <img src="{{ qr_link }}" alt="" width="320"  height="320">
</div>
{% endblock %}

OldSuply/pedidos/templates/payment_pix_fix.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="bg-light container">
    <h2>Obrigado por querer comprar em nossa loja.</h2>
    <p>Infelizmente nossos métodos de pagamentos ainda não estão concluídos, no entanto, para concluir a compra, faça um pix no valor total da compra e nos envie o comprovante
        em nosso WhatsApp com o ID da compra, para que possamos estar validando e enviando o pedido o mais rápido possível.
    </p>
    <div class="row">
        <div class="col"> 
            <h3>Nosso QRCode</h3>
            <img src="{% static 'pedidos/img/mercadopago_pixQr.png' %}" alt="Pix da loja" width="320" height="320">
        </div>
        <div class="col">
            <h4>Nossa chave Pix: <b>(35) 987039611 </b></h4>
            <h4>Nosso WhatsApp: <b>(35) 987039611 </b></h4>
            <h4>ID do seu pedido: <b>{{ order.order_id }}</b></h4>
            <h4>Valor do seu pedido : <b>R${{ order.total }}</b></h4>
        </div>
    </div>
</div>
{% endblock %}